services:
  web:
    build: ./docker/
    command: npm run dev -- --host
    ports:
      - "3000:5173"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}